---
- hosts: all
  become: yes

- name: Copying and executing a script
  hosts: all
  become: yes
  tasks:
     #- name: Transfer the script
     #  copy: src=/export/home/linadmin/automation/scripts/precheck_script.sh dest=/export/home/sysadmin mode=0775

     - name: Execute the script
       shell: /home/naveen/automation/scripts/precheck_script.sh "{{Request_Number}}"
